version: "3.9"
services:
    java_db:
        container_name: java_db
        image: postgres
        environment:
            POSTGRES_USER: energytop
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: energytopDB
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always
volumes:
    pgdata: {}
